-- ============================================================
-- Auto-generated seed: plan_days + plan_sections + plan_items
-- Generated by scripts/generate-seed.js
-- ============================================================

-- ── plan_days ────────────────────────────────────────────────
insert into public.plan_days (day_number, phase, dsa_description, design_description, behavioral_description)
values
  (1, 'P1', 'Arrays/Hashing patterns: Two Sum, Group Anagrams, Top K Frequent. Time-box each at 25 min.', 'LLD basics: SOLID principles deep-dive. Write notes with code examples for each.', 'Inventory: list 8-10 significant projects from your 12 YoE. Tag each with possible STAR themes.'),
  (2, 'P1', 'Two Pointers: Valid Palindrome, 3Sum, Container With Most Water, Trapping Rain Water.', 'LLD: Design a Parking Lot. Write out classes, relationships, write code in your strongest language.', 'Top 5 stories: Draft Situation+Task for each in 3-4 lines.'),
  (3, 'P1', 'Sliding Window: Best Time Buy/Sell Stock, Longest Substring Without Repeat, Min Window Substring.', 'LLD: Design Snake & Ladder / Tic Tac Toe. Focus on extensibility.', 'STAR drafting: Draft Action+Result for the 5 stories. Quantify impact wherever possible.'),
  (4, 'P1', 'Stack: Valid Parens, Min Stack, Daily Temperatures, Largest Rectangle in Histogram.', 'Design Patterns: Strategy, Observer, Factory. Code real examples, not toy ones.', 'Amazon LP mapping: map each story to 1-3 Leadership Principles.'),
  (5, 'P1', 'Binary Search variants: Search Rotated Sorted Array, Find Min in Rotated, Median of Two Sorted Arrays.', 'Design Patterns: Singleton (with thread safety), Builder, Decorator. Code examples.', 'Tell-me-about-yourself: Practice 90 sec version + 3 min version.'),
  (6, 'P1', 'Linked List: Reverse Linked List, Merge K Sorted Lists, LRU Cache, Reorder List.', 'LLD: Design an LRU Cache with thread safety. Implement in code (Doubly LL + HashMap).', 'Mock recording: ''Tell me about a time you disagreed with a leader''.'),
  (7, 'P1', 'Trees Part 1: Invert Binary Tree, Max Depth, Same Tree, Diameter of Binary Tree, Balanced Binary Tree.', 'HLD primer: Latency numbers, throughput vs latency, CAP theorem, ACID vs BASE.', 'Reason for switching: Write and polish for 12 YoE narrative.'),
  (8, 'P1', 'Trees Part 2: BFS Level Order, Right Side View, LCA of Binary Tree, Validate BST.', 'HLD primer: Load balancing, reverse proxies, CDN, caching strategies (cache-aside, write-through, write-back).', 'Most challenging technical problem: Draft full STAR.'),
  (9, 'P1', 'Trees Part 3: Serialize/Deserialize Binary Tree, Path Sum III, Kth Smallest in BST, Construct from Preorder+Inorder.', 'HLD: SQL vs NoSQL, indexes, B-trees, LSM-trees.', 'Big risk story: Draft STAR for ''Time you took a big risk''.'),
  (10, 'P1', 'Heap/Priority Queue: Top K Frequent Elements, K Closest Points to Origin, Find Median from Data Stream, Task Scheduler.', 'LLD: Design Library Management System. Focus on entity modeling and API design.', 'Mentorship story: ''Time you mentored or grew an engineer''.'),
  (11, 'P1', 'Backtracking: Subsets, Permutations, Combination Sum, Word Search, N-Queens.', 'HLD: Sharding, replication (master-slave, master-master), consistent hashing.', 'Failure story: Draft STAR for failure and what you learned. Avoid trivial failures.'),
  (12, 'P1', 'Graphs Part 1: Number of Islands, Clone Graph, Course Schedule, Pacific Atlantic Water Flow.', 'HLD: Message queues — Kafka vs RabbitMQ vs SQS. Pub-sub vs queue.', 'Conflict story: ''Conflict with peer or manager''. Draft. Tone matters.'),
  (13, 'P1', 'Graphs Part 2: Topological Sort, Word Ladder, Alien Dictionary, Min Cost Connect Points (MST).', 'LLD: Design ATM / Vending Machine — state machine pattern.', 'Behavioral mock: Pick 3 prompts from Amazon LP list, answer aloud.'),
  (14, 'P1', 'DP Part 1 (1D): Climbing Stairs, House Robber, House Robber II, Coin Change, Word Break, Longest Increasing Subsequence.', 'HLD: Rate limiter design. Token bucket, leaky bucket, sliding window. Code the algorithm too.', 'Behavioral mock: Googleyness and leadership prompts.'),
  (15, 'P1', 'Phase 1 review: Re-solve 5 random problems from Days 1-14 cold. Identify patterns you missed.', 'Phase 1 review: Refactor at least one LLD design from Days 2, 6, 10, 13 for cleaner abstraction.', 'Phase 1 retrospective: Write what''s still weak and adjust Phase 2 priorities.'),
  (16, 'P2', 'DP Part 2 (2D): Longest Common Subsequence, Edit Distance, Unique Paths, 0/1 Knapsack.', 'HLD Case Study — URL Shortener: Design TinyURL end-to-end (reqs, capacity, API, schema, scaling).', 'Refine top 3 stories with quantified impact. Replace ''I did X'' with ''I led X resulting in Y''.'),
  (17, 'P2', 'DP Part 3 (Hard): Longest Palindromic Subsequence, Distinct Subsequences, Burst Balloons, Regular Expression Matching.', 'URL Shortener deep-dive: Base62 vs hashing, DB choice, cache design, analytics layer.', 'Story drill: 2 prompts cold, 5 min each, no notes.'),
  (18, 'P2', 'Intervals: Merge Intervals, Insert Interval, Non-overlapping Intervals, Meeting Rooms II.', 'HLD Case Study — File Storage: Design Pastebin / Dropbox. Focus on storage, metadata, chunking.', 'Manager round: ''How do you give critical feedback?'' Draft answer.'),
  (19, 'P2', 'Greedy: Jump Game, Gas Station, Hand of Straights, Merge Triplets to Form Target.', 'HLD Case Study — Twitter/News Feed: Fan-out write vs fan-out read trade-offs.', 'Manager round: ''How do you handle an underperformer?'' Draft.'),
  (20, 'P2', 'Bit Manipulation + Math: Single Number, Counting Bits, Reverse Bits, Missing Number, Pow(x,n).', 'Twitter/Feed deep-dive: Timeline storage, celebrity problem, push vs pull, Redis sorted sets.', 'Manager round: ''How do you prioritize work for your team?'' Draft.'),
  (21, 'P2', 'Weekend hard set: Solve 1 hard problem from each of DP, Graphs, Trees. 45 min each then study optimal.', 'HLD Case Study — WhatsApp/Chat: Long polling vs WebSocket vs SSE. Online presence.', 'Behavioral mock: 30 min session, 3 stories with friend or AI.'),
  (22, 'P2', 'Tagged — Google/Meta: 10 LeetCode problems tagged for your primary target company.', 'WhatsApp deep-dive: Group chat, message ordering, end-to-end encryption basics.', 'Biggest impact story: Refine ''biggest impact you''ve had''. This is THE story for senior level.'),
  (23, 'P2', 'Tagged — Amazon: 10 LC problems tagged Amazon. Note Amazon style: graph/heap/string-heavy.', 'HLD Case Study — Uber/Ride-sharing: Geohashing, quad-trees, matching algorithm.', 'Influence without authority story: Critical at staff level.'),
  (24, 'P2', 'Tries: Implement Trie, Design Add+Search Words, Word Search II.', 'Uber deep-dive: Real-time location updates, surge pricing, ETA computation.', 'Biggest weakness: Prepare a real one with concrete improvement steps.'),
  (25, 'P2', 'Advanced Graphs: Network Delay Time (Dijkstra), Cheapest Flights K Stops, Swim in Rising Water.', 'LLD Deep Dive — Splitwise: Expense sharing and debt simplification algorithm.', 'Bar Raiser prep: 4 LP-mapped stories rapid fire (if Amazon target).'),
  (26, 'P2', 'Strings: Longest Palindromic Substring, Minimum Window Substring revisit, KMP string matching.', 'HLD Case Study — YouTube/Netflix: Video upload pipeline, encoding, CDN, recommendations.', 'Tech lead question: ''How do you make a tech decision when team disagrees?'''),
  (27, 'P2', 'Union-Find: Number of Connected Components, Redundant Connection, Accounts Merge.', 'YouTube deep-dive: Storage at scale, DASH/HLS streaming, view count consistency.', 'Tech lead question: ''How do you handle technical debt vs feature delivery?'''),
  (28, 'P2', 'Mock Interview #1: 60 min DSA session. 2 problems on LeetCode in interview mode or paid platform.', 'HLD Case Study — Search Autocomplete: Trie at scale + search ranking basics.', 'Self-review mock answers: Are you concise? Cut filler words.'),
  (29, 'P2', 'Review Mock #1 weaknesses. Re-solve missed problems. Study optimal patterns.', 'HLD: Idempotency, distributed transactions, saga pattern, two-phase commit.', 'Critical incident story: ''Time you owned an outage''. Strong senior signal.'),
  (30, 'P2', 'Sliding Window hard: Subarrays with K Different Integers, Minimum Window Substring revisit.', 'HLD: Observability — logs, metrics, traces. SLO/SLI/SLA definitions.', 'Why this company: Refine for top 2 target companies. Specific not generic.'),
  (31, 'P2', 'Graph hard set: Word Ladder II, Bus Routes, Reconstruct Itinerary.', 'HLD Case Study — Notification System: Multi-channel, dedup, rate limiting per user.', 'Simplification story: ''Time you simplified something complex'' — architecture or process.'),
  (32, 'P2', 'DP hard set: Best Time to Buy/Sell Stock with Cooldown, Best Time to Buy/Sell Stock IV, Dungeon Game.', 'HLD Case Study — Distributed Cache (Redis): Eviction, replication, hot-key problem.', 'Cross-team collaboration story: ''Dependency you led across teams''.'),
  (33, 'P2', 'Heap + Greedy combo: IPO, Reorganize String, Furthest Building You Can Reach.', 'HLD: API design — REST vs gRPC vs GraphQL. Versioning. Pagination strategies.', 'Story drill: 4 prompts, 4 min each, time yourself strictly.'),
  (34, 'P2', 'Matrix problems: Spiral Matrix, Rotate Image, Set Matrix Zeros, Word Search.', 'HLD Case Study — Google Drive: Collaborative editing primer (OT vs CRDT awareness).', 'Amazon LP final pass: Cover 14-16 stories minimum if targeting Amazon.'),
  (35, 'P2', 'Phase 2 retrospective: Identify 2 weakest topics. Plan extra hours for them in Phase 3.', 'HLD Case Study — Metrics/Monitoring System: Design Datadog-style system.', 'Read failure mode stories online (Pragmatic Engineer, Levels.fyi) to recalibrate bar.'),
  (36, 'P3', 'Mock Interview #2: 60 min DSA, recorded. Use Pramp / Interviewing.io / friend.', 'HLD Mock #1: 45 min on a system you haven''t designed yet. Record yourself.', 'HLD mock review: Cover reqs, capacity, API, data model, HLD, deep-dive, trade-offs?'),
  (37, 'P3', 'Review Mock #2: Re-solve problems. Study editorial. Did you communicate while coding?', 'HLD Case Study — Instagram: Photo sharing, feed algorithm, storage tiering.', 'Why leaving current role: Polish answer — never blame, frame forward.'),
  (38, 'P3', 'Tagged — Company #1: 10 LC problems for your primary target, focus on 30-day frequency.', 'HLD Case Study — Distributed Logging: ELK stack at scale.', 'Behavioral mock round: 30 min, 4 stories, get harsh feedback.'),
  (39, 'P3', 'Tagged — Company #2: 10 LC problems for your secondary target.', 'HLD: Multi-region active-active vs active-passive. Disaster recovery (RPO/RTO).', 'Record tell-me-about-yourself: Watch back, fix awkwardness.'),
  (40, 'P3', 'Hard problem deep-dive: Pick 1 LC Hard, spend 90 min understanding 3 different solutions.', 'LLD Mock: Design Stack Overflow / Q&A site code-level. 60 min, write actual code.', 'Pushback story: ''Time you said no to a senior leader / pushed back''. Staff level signal.'),
  (41, 'P3', 'Mock Interview #3: 90 min DSA — 2 mediums + 1 hard on Pramp or Interviewing.io.', 'HLD Case Study — Slack/Discord: Channels, presence at scale, message search.', 'Mock #3 review: Are you starting with brute force? Communicating trade-offs?'),
  (42, 'P3', 'Weekend stamina test: 3 x 45 min DSA mock sessions back-to-back. Endurance focus.', 'HLD Mock #2: 60 min on a different system from mock #1.', 'Behavioral mock: 5 prompts, 5 min each. Sustain energy across all 5.'),
  (43, 'P3', 'Recovery day: Re-solve 5 problems you''ve struggled with most. Spaced repetition.', 'HLD Mock #2 review: List 5 things you''d say differently next time.', 'Salary/leveling research: levels.fyi, Blind, Glassdoor for target companies.'),
  (44, 'P3', 'Speed drill — Trees + Graphs: 6 problems, 25 min each. Speed focus.', 'HLD Case Study — Online Code Editor: Sandboxing, real-time execution (Leetcode/Replit).', 'Negotiation prep: Read ''Ten Rules for Negotiating'' (haseebq) if not done.'),
  (45, 'P3', 'Speed drill — DP + Backtracking: 5 problems, 30 min each.', 'HLD Case Study — Booking System: Inventory locking, double-booking prevention (Airbnb/Hotel).', 'Questions for interviewer: Prepare 3 sharp questions per round type.'),
  (46, 'P3', 'Mock Interview #4: DSA focused on your weakest topic from previous mocks.', 'LLD Mock — Movie Booking System: BookMyShow with concurrency around seat locking.', 'Self-recorded behavioral: 30 min, 5 prompts. Watch back.'),
  (47, 'P3', 'Review Mock #4: Patterns missed? Speed issues? Communication gaps?', 'HLD: Feature flags, A/B testing infra, gradual rollouts. Senior signal.', 'STAR pruning: Take a 6 min answer and cut it to 3 min without losing impact.'),
  (48, 'P3', 'Onsite simulation: 4 x 45 min DSA + 1 hour break + behavioral. Full endurance test.', 'Review existing case study notes. No new HLD content today.', 'Endurance assessment: How was hour 5? Plan rest before real onsite.'),
  (49, 'P3', 'Light DSA day: 3 LC mediums, no time pressure. Read editorials.', 'HLD Case Study — Payment System: Idempotency, double-charge prevention, ledger.', 'Final story bank: Compile 12-15 polished stories indexed by theme.'),
  (50, 'P3', 'Phase 3 retrospective: Are mock scores trending up? Identify final 2-3 gaps.', 'HLD Case Study — Distributed Job Scheduler: Cron at scale.', 'Behavioral mock with senior engineer: Get honest feedback.'),
  (51, 'P4', 'Must-know set: LRU Cache, LFU Cache, Find Median from Data Stream, Trapping Rain Water.', 'HLD speed-run: Pick 5 case studies from your notes, do 10-min outlines each.', 'Read engineering blogs: Anthropic/Google/Meta — have a recent thing to discuss.'),
  (52, 'P4', 'Tagged — Final pass: 8 problems for your top target, mix of high-frequency tags.', 'Target company HLD: Design a system specific to your target company''s product.', 'Top 5 stories final pass: Record once, listen for filler words (um, like, sort of).'),
  (53, 'P4', 'Mock Interview #5: Full DSA simulation. 60 min, recorded. Solo or paid platform.', 'HLD Mock #3: Focus on deep-dive component, not just high level.', 'Behavioral mock #3: Timed, 30 min, recorded.'),
  (54, 'P4', 'Review all mocks: Identify common gaps. Do 3 problems on those gaps.', 'HLD weak areas review: Capacity estimation accuracy, deep-dive specificity.', 'Crisis stories: Compile top 3 — performance issues, outages, conflicts. Polish them.'),
  (55, 'P4', 'Light: 2 LC mediums you''ve solved before, time them, aim for under 20 min each.', 'HLD: DB internals deep-dive — B-tree vs LSM, isolation levels (common follow-ups).', 'Question bank: Refresh your questions for each interviewer type.'),
  (56, 'P4', 'Speed drill: 5 LC easies in 60 min. Should feel automatic now.', 'LLD speed-run: Re-implement Parking Lot, LRU Cache, BookMyShow seat locking from memory.', 'Negotiation script: Practice with specific numbers, ranges, walk-away point.'),
  (57, 'P4', 'Cool-down: Re-solve 3 problems from Day 1. Measure how much faster you are.', 'HLD numbers review: Latency by component, QPS estimation, storage math.', 'Why FAANG / why now: Polish your 12 YoE story arc.'),
  (58, 'P4', 'Light: 2 problems max. Don''t burn out.', 'HLD outlines: 2 case studies in 30 min each, outlines only.', 'Behavioral final mock: Go in fresh, treat as real interview.'),
  (59, 'P4', 'Rest day: Review notes only. Walk, exercise, sleep early. No new problems.', 'Rest day: Skim HLD case study one-liners only.', 'Mental prep: Visualize the interview going well. Check logistics.'),
  (60, 'P4', 'Warm-up: 1 easy problem for confidence. Then STOP.', 'Review your HLD framework one-pager only.', 'Apply and schedule interviews. You''re ready.')
on conflict (day_number) do update
  set phase = excluded.phase,
      dsa_description = excluded.dsa_description,
      design_description = excluded.design_description,
      behavioral_description = excluded.behavioral_description;

-- ── Clear & re-seed sections / items ────────────────────────
delete from public.plan_sections;

-- Day 1 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (1, 'DSA', 'Arrays/Hashing patterns', 'Time-box each at 25 min', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Two Sum', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Group Anagrams', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Top K Frequent', 2);
end $$;

-- Day 1 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (1, 'DESIGN', 'LLD basics', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'SOLID principles deep-dive. Write notes with code examples for each', 0);
end $$;

-- Day 1 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (1, 'BEHAVIORAL', 'Inventory', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'list 8-10 significant projects from your 12 YoE. Tag each with possible STAR themes', 0);
end $$;

-- Day 2 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (2, 'DSA', 'Two Pointers', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Valid Palindrome', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '3Sum', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Container With Most Water', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Trapping Rain Water', 3);
end $$;

-- Day 2 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (2, 'DESIGN', 'LLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design a Parking Lot. Write out classes, relationships, write code in your strongest language', 0);
end $$;

-- Day 2 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (2, 'BEHAVIORAL', 'Top 5 stories', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Draft Situation+Task for each in 3-4 lines', 0);
end $$;

-- Day 3 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (3, 'DSA', 'Sliding Window', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Best Time Buy/Sell Stock', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Longest Substring Without Repeat', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Min Window Substring', 2);
end $$;

-- Day 3 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (3, 'DESIGN', 'LLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design Snake & Ladder / Tic Tac Toe. Focus on extensibility', 0);
end $$;

-- Day 3 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (3, 'BEHAVIORAL', 'STAR drafting', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Draft Action+Result for the 5 stories. Quantify impact wherever possible', 0);
end $$;

-- Day 4 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (4, 'DSA', 'Stack', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Valid Parens', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Min Stack', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Daily Temperatures', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Largest Rectangle in Histogram', 3);
end $$;

-- Day 4 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (4, 'DESIGN', 'Design Patterns', 'Code real examples, not toy ones', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Strategy, Observer, Factory', 0);
end $$;

-- Day 4 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (4, 'BEHAVIORAL', 'Amazon LP mapping', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'map each story to 1-3 Leadership Principles', 0);
end $$;

-- Day 5 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (5, 'DSA', 'Binary Search variants', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Search Rotated Sorted Array', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Find Min in Rotated', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Median of Two Sorted Arrays', 2);
end $$;

-- Day 5 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (5, 'DESIGN', 'Design Patterns', 'Code examples', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Singleton (with thread safety), Builder, Decorator', 0);
end $$;

-- Day 5 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (5, 'BEHAVIORAL', 'Tell-me-about-yourself', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Practice 90 sec version + 3 min version', 0);
end $$;

-- Day 6 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (6, 'DSA', 'Linked List', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Reverse Linked List', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Merge K Sorted Lists', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'LRU Cache', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Reorder List', 3);
end $$;

-- Day 6 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (6, 'DESIGN', 'LLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design an LRU Cache with thread safety. Implement in code (Doubly LL + HashMap)', 0);
end $$;

-- Day 6 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (6, 'BEHAVIORAL', 'Mock recording', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''Tell me about a time you disagreed with a leader''', 0);
end $$;

-- Day 7 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (7, 'DSA', 'Trees Part 1', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Invert Binary Tree', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Max Depth', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Same Tree', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Diameter of Binary Tree', 3);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Balanced Binary Tree', 4);
end $$;

-- Day 7 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (7, 'DESIGN', 'HLD primer', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Latency numbers, throughput vs latency, CAP theorem, ACID vs BASE', 0);
end $$;

-- Day 7 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (7, 'BEHAVIORAL', 'Reason for switching', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Write and polish for 12 YoE narrative', 0);
end $$;

-- Day 8 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (8, 'DSA', 'Trees Part 2', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'BFS Level Order', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Right Side View', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'LCA of Binary Tree', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Validate BST', 3);
end $$;

-- Day 8 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (8, 'DESIGN', 'HLD primer', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Load balancing, reverse proxies, CDN, caching strategies (cache-aside, write-through, write-back)', 0);
end $$;

-- Day 8 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (8, 'BEHAVIORAL', 'Most challenging technical problem', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Draft full STAR', 0);
end $$;

-- Day 9 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (9, 'DSA', 'Trees Part 3', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Serialize/Deserialize Binary Tree', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Path Sum III', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Kth Smallest in BST', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Construct from Preorder+Inorder', 3);
end $$;

-- Day 9 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (9, 'DESIGN', 'HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'SQL vs NoSQL, indexes, B-trees, LSM-trees', 0);
end $$;

-- Day 9 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (9, 'BEHAVIORAL', 'Big risk story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Draft STAR for ''Time you took a big risk''', 0);
end $$;

-- Day 10 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (10, 'DSA', 'Heap/Priority Queue', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Top K Frequent Elements', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'K Closest Points to Origin', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Find Median from Data Stream', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Task Scheduler', 3);
end $$;

-- Day 10 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (10, 'DESIGN', 'LLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design Library Management System. Focus on entity modeling and API design', 0);
end $$;

-- Day 10 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (10, 'BEHAVIORAL', 'Mentorship story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''Time you mentored or grew an engineer''', 0);
end $$;

-- Day 11 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (11, 'DSA', 'Backtracking', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Subsets', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Permutations', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Combination Sum', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Word Search', 3);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'N-Queens', 4);
end $$;

-- Day 11 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (11, 'DESIGN', 'HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Sharding, replication (master-slave, master-master), consistent hashing', 0);
end $$;

-- Day 11 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (11, 'BEHAVIORAL', 'Failure story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Draft STAR for failure and what you learned. Avoid trivial failures', 0);
end $$;

-- Day 12 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (12, 'DSA', 'Graphs Part 1', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Number of Islands', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Clone Graph', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Course Schedule', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Pacific Atlantic Water Flow', 3);
end $$;

-- Day 12 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (12, 'DESIGN', 'HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Message queues — Kafka vs RabbitMQ vs SQS. Pub-sub vs queue', 0);
end $$;

-- Day 12 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (12, 'BEHAVIORAL', 'Conflict story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''Conflict with peer or manager''. Draft. Tone matters', 0);
end $$;

-- Day 13 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (13, 'DSA', 'Graphs Part 2', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Topological Sort', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Word Ladder', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Alien Dictionary', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Min Cost Connect Points (MST)', 3);
end $$;

-- Day 13 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (13, 'DESIGN', 'LLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design ATM / Vending Machine — state machine pattern', 0);
end $$;

-- Day 13 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (13, 'BEHAVIORAL', 'Behavioral mock', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Pick 3 prompts from Amazon LP list, answer aloud', 0);
end $$;

-- Day 14 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (14, 'DSA', 'DP Part 1 (1D)', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Climbing Stairs', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'House Robber', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'House Robber II', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Coin Change', 3);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Word Break', 4);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Longest Increasing Subsequence', 5);
end $$;

-- Day 14 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (14, 'DESIGN', 'HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Rate limiter design. Token bucket, leaky bucket, sliding window. Code the algorithm too', 0);
end $$;

-- Day 14 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (14, 'BEHAVIORAL', 'Behavioral mock', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Googleyness and leadership prompts', 0);
end $$;

-- Day 15 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (15, 'DSA', 'Phase 1 review', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Re-solve 5 random problems from Days 1-14 cold. Identify patterns you missed', 0);
end $$;

-- Day 15 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (15, 'DESIGN', 'Phase 1 review', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Refactor at least one LLD design from Days 2, 6, 10, 13 for cleaner abstraction', 0);
end $$;

-- Day 15 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (15, 'BEHAVIORAL', 'Phase 1 retrospective', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Write what''s still weak and adjust Phase 2 priorities', 0);
end $$;

-- Day 16 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (16, 'DSA', 'DP Part 2 (2D)', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Longest Common Subsequence', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Edit Distance', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Unique Paths', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '0/1 Knapsack', 3);
end $$;

-- Day 16 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (16, 'DESIGN', 'HLD Case Study — URL Shortener', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design TinyURL end-to-end (reqs, capacity, API, schema, scaling)', 0);
end $$;

-- Day 16 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (16, 'BEHAVIORAL', 'Behavioral Task', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Refine top 3 stories with quantified impact. Replace ''I did X'' with ''I led X resulting in Y''', 0);
end $$;

-- Day 17 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (17, 'DSA', 'DP Part 3 (Hard)', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Longest Palindromic Subsequence', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Distinct Subsequences', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Burst Balloons', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Regular Expression Matching', 3);
end $$;

-- Day 17 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (17, 'DESIGN', 'URL Shortener deep-dive', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Base62 vs hashing, DB choice, cache design, analytics layer', 0);
end $$;

-- Day 17 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (17, 'BEHAVIORAL', 'Story drill', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '2 prompts cold, 5 min each, no notes', 0);
end $$;

-- Day 18 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (18, 'DSA', 'Intervals', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Merge Intervals', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Insert Interval', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Non-overlapping Intervals', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Meeting Rooms II', 3);
end $$;

-- Day 18 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (18, 'DESIGN', 'HLD Case Study — File Storage', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design Pastebin / Dropbox. Focus on storage, metadata, chunking', 0);
end $$;

-- Day 18 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (18, 'BEHAVIORAL', 'Manager round', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''How do you give critical feedback?'' Draft answer', 0);
end $$;

-- Day 19 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (19, 'DSA', 'Greedy', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Jump Game', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Gas Station', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Hand of Straights', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Merge Triplets to Form Target', 3);
end $$;

-- Day 19 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (19, 'DESIGN', 'HLD Case Study — Twitter/News Feed', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Fan-out write vs fan-out read trade-offs', 0);
end $$;

-- Day 19 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (19, 'BEHAVIORAL', 'Manager round', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''How do you handle an underperformer?'' Draft', 0);
end $$;

-- Day 20 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (20, 'DSA', 'Bit Manipulation + Math', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Single Number', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Counting Bits', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Reverse Bits', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Missing Number', 3);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Pow(x', 4);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'n)', 5);
end $$;

-- Day 20 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (20, 'DESIGN', 'Twitter/Feed deep-dive', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Timeline storage, celebrity problem, push vs pull, Redis sorted sets', 0);
end $$;

-- Day 20 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (20, 'BEHAVIORAL', 'Manager round', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''How do you prioritize work for your team?'' Draft', 0);
end $$;

-- Day 21 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (21, 'DSA', 'Weekend hard set', '45 min each then study optimal', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Solve 1 hard problem from each of DP', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Graphs', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Trees', 2);
end $$;

-- Day 21 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (21, 'DESIGN', 'HLD Case Study — WhatsApp/Chat', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Long polling vs WebSocket vs SSE. Online presence', 0);
end $$;

-- Day 21 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (21, 'BEHAVIORAL', 'Behavioral mock', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '30 min session, 3 stories with friend or AI', 0);
end $$;

-- Day 22 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (22, 'DSA', 'Tagged — Google/Meta', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '10 LeetCode problems tagged for your primary target company', 0);
end $$;

-- Day 22 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (22, 'DESIGN', 'WhatsApp deep-dive', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Group chat, message ordering, end-to-end encryption basics', 0);
end $$;

-- Day 22 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (22, 'BEHAVIORAL', 'Biggest impact story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Refine ''biggest impact you''ve had''. This is THE story for senior level', 0);
end $$;

-- Day 23 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (23, 'DSA', 'Tagged — Amazon', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '10 LC problems tagged Amazon. Note Amazon style: graph/heap/string-heavy', 0);
end $$;

-- Day 23 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (23, 'DESIGN', 'HLD Case Study — Uber/Ride-sharing', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Geohashing, quad-trees, matching algorithm', 0);
end $$;

-- Day 23 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (23, 'BEHAVIORAL', 'Influence without authority story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Critical at staff level', 0);
end $$;

-- Day 24 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (24, 'DSA', 'Tries', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Implement Trie', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design Add+Search Words', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Word Search II', 2);
end $$;

-- Day 24 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (24, 'DESIGN', 'Uber deep-dive', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Real-time location updates, surge pricing, ETA computation', 0);
end $$;

-- Day 24 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (24, 'BEHAVIORAL', 'Biggest weakness', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Prepare a real one with concrete improvement steps', 0);
end $$;

-- Day 25 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (25, 'DSA', 'Advanced Graphs', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Network Delay Time (Dijkstra)', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Cheapest Flights K Stops', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Swim in Rising Water', 2);
end $$;

-- Day 25 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (25, 'DESIGN', 'LLD Deep Dive — Splitwise', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Expense sharing and debt simplification algorithm', 0);
end $$;

-- Day 25 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (25, 'BEHAVIORAL', 'Bar Raiser prep', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '4 LP-mapped stories rapid fire (if Amazon target)', 0);
end $$;

-- Day 26 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (26, 'DSA', 'Strings', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Longest Palindromic Substring', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Minimum Window Substring revisit', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'KMP string matching', 2);
end $$;

-- Day 26 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (26, 'DESIGN', 'HLD Case Study — YouTube/Netflix', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Video upload pipeline, encoding, CDN, recommendations', 0);
end $$;

-- Day 26 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (26, 'BEHAVIORAL', 'Tech lead question', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''How do you make a tech decision when team disagrees?''', 0);
end $$;

-- Day 27 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (27, 'DSA', 'Union-Find', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Number of Connected Components', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Redundant Connection', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Accounts Merge', 2);
end $$;

-- Day 27 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (27, 'DESIGN', 'YouTube deep-dive', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Storage at scale, DASH/HLS streaming, view count consistency', 0);
end $$;

-- Day 27 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (27, 'BEHAVIORAL', 'Tech lead question', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''How do you handle technical debt vs feature delivery?''', 0);
end $$;

-- Day 28 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (28, 'DSA', 'Mock Interview #1', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '60 min DSA session. 2 problems on LeetCode in interview mode or paid platform', 0);
end $$;

-- Day 28 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (28, 'DESIGN', 'HLD Case Study — Search Autocomplete', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Trie at scale + search ranking basics', 0);
end $$;

-- Day 28 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (28, 'BEHAVIORAL', 'Self-review mock answers', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Are you concise? Cut filler words', 0);
end $$;

-- Day 29 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (29, 'DSA', 'Practice', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Review Mock #1 weaknesses. Re-solve missed problems. Study optimal patterns', 0);
end $$;

-- Day 29 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (29, 'DESIGN', 'HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Idempotency, distributed transactions, saga pattern, two-phase commit', 0);
end $$;

-- Day 29 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (29, 'BEHAVIORAL', 'Critical incident story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''Time you owned an outage''. Strong senior signal', 0);
end $$;

-- Day 30 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (30, 'DSA', 'Sliding Window hard', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Subarrays with K Different Integers', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Minimum Window Substring revisit', 1);
end $$;

-- Day 30 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (30, 'DESIGN', 'HLD', 'SLO/SLI/SLA definitions', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Observability — logs, metrics, traces', 0);
end $$;

-- Day 30 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (30, 'BEHAVIORAL', 'Why this company', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Refine for top 2 target companies. Specific not generic', 0);
end $$;

-- Day 31 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (31, 'DSA', 'Graph hard set', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Word Ladder II', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Bus Routes', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Reconstruct Itinerary', 2);
end $$;

-- Day 31 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (31, 'DESIGN', 'HLD Case Study — Notification System', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Multi-channel, dedup, rate limiting per user', 0);
end $$;

-- Day 31 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (31, 'BEHAVIORAL', 'Simplification story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''Time you simplified something complex'' — architecture or process', 0);
end $$;

-- Day 32 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (32, 'DSA', 'DP hard set', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Best Time to Buy/Sell Stock with Cooldown', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Best Time to Buy/Sell Stock IV', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Dungeon Game', 2);
end $$;

-- Day 32 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (32, 'DESIGN', 'HLD Case Study — Distributed Cache (Redis)', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Eviction, replication, hot-key problem', 0);
end $$;

-- Day 32 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (32, 'BEHAVIORAL', 'Cross-team collaboration story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''Dependency you led across teams''', 0);
end $$;

-- Day 33 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (33, 'DSA', 'Heap + Greedy combo', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'IPO', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Reorganize String', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Furthest Building You Can Reach', 2);
end $$;

-- Day 33 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (33, 'DESIGN', 'HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'API design — REST vs gRPC vs GraphQL. Versioning. Pagination strategies', 0);
end $$;

-- Day 33 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (33, 'BEHAVIORAL', 'Story drill', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '4 prompts, 4 min each, time yourself strictly', 0);
end $$;

-- Day 34 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (34, 'DSA', 'Matrix problems', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Spiral Matrix', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Rotate Image', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Set Matrix Zeros', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Word Search', 3);
end $$;

-- Day 34 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (34, 'DESIGN', 'HLD Case Study — Google Drive', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Collaborative editing primer (OT vs CRDT awareness)', 0);
end $$;

-- Day 34 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (34, 'BEHAVIORAL', 'Amazon LP final pass', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Cover 14-16 stories minimum if targeting Amazon', 0);
end $$;

-- Day 35 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (35, 'DSA', 'Phase 2 retrospective', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Identify 2 weakest topics. Plan extra hours for them in Phase 3', 0);
end $$;

-- Day 35 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (35, 'DESIGN', 'HLD Case Study — Metrics/Monitoring System', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design Datadog-style system', 0);
end $$;

-- Day 35 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (35, 'BEHAVIORAL', 'Behavioral Task', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Read failure mode stories online (Pragmatic Engineer, Levels.fyi) to recalibrate bar', 0);
end $$;

-- Day 36 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (36, 'DSA', 'Mock Interview #2', 'Use Pramp / Interviewing.io / friend', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '60 min DSA', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'recorded', 1);
end $$;

-- Day 36 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (36, 'DESIGN', 'HLD Mock #1', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '45 min on a system you haven''t designed yet. Record yourself', 0);
end $$;

-- Day 36 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (36, 'BEHAVIORAL', 'HLD mock review', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Cover reqs, capacity, API, data model, HLD, deep-dive, trade-offs?', 0);
end $$;

-- Day 37 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (37, 'DSA', 'Review Mock #2', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Re-solve problems. Study editorial. Did you communicate while coding?', 0);
end $$;

-- Day 37 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (37, 'DESIGN', 'HLD Case Study — Instagram', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Photo sharing, feed algorithm, storage tiering', 0);
end $$;

-- Day 37 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (37, 'BEHAVIORAL', 'Why leaving current role', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Polish answer — never blame, frame forward', 0);
end $$;

-- Day 38 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (38, 'DSA', 'Tagged — Company #1', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '10 LC problems for your primary target', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'focus on 30-day frequency', 1);
end $$;

-- Day 38 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (38, 'DESIGN', 'HLD Case Study — Distributed Logging', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'ELK stack at scale', 0);
end $$;

-- Day 38 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (38, 'BEHAVIORAL', 'Behavioral mock round', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '30 min, 4 stories, get harsh feedback', 0);
end $$;

-- Day 39 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (39, 'DSA', 'Tagged — Company #2', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '10 LC problems for your secondary target', 0);
end $$;

-- Day 39 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (39, 'DESIGN', 'HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Multi-region active-active vs active-passive. Disaster recovery (RPO/RTO)', 0);
end $$;

-- Day 39 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (39, 'BEHAVIORAL', 'Record tell-me-about-yourself', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Watch back, fix awkwardness', 0);
end $$;

-- Day 40 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (40, 'DSA', 'Hard problem deep-dive', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Pick 1 LC Hard', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'spend 90 min understanding 3 different solutions', 1);
end $$;

-- Day 40 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (40, 'DESIGN', 'LLD Mock', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design Stack Overflow / Q&A site code-level. 60 min, write actual code', 0);
end $$;

-- Day 40 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (40, 'BEHAVIORAL', 'Pushback story', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '''Time you said no to a senior leader / pushed back''. Staff level signal', 0);
end $$;

-- Day 41 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (41, 'DSA', 'Mock Interview #3', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '90 min DSA — 2 mediums + 1 hard on Pramp or Interviewing.io', 0);
end $$;

-- Day 41 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (41, 'DESIGN', 'HLD Case Study — Slack/Discord', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Channels, presence at scale, message search', 0);
end $$;

-- Day 41 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (41, 'BEHAVIORAL', 'Mock #3 review', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Are you starting with brute force? Communicating trade-offs?', 0);
end $$;

-- Day 42 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (42, 'DSA', 'Weekend stamina test', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '3 x 45 min DSA mock sessions back-to-back. Endurance focus', 0);
end $$;

-- Day 42 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (42, 'DESIGN', 'HLD Mock #2', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '60 min on a different system from mock #1', 0);
end $$;

-- Day 42 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (42, 'BEHAVIORAL', 'Behavioral mock', 'Sustain energy across all 5', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '5 prompts, 5 min each', 0);
end $$;

-- Day 43 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (43, 'DSA', 'Recovery day', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Re-solve 5 problems you''ve struggled with most. Spaced repetition', 0);
end $$;

-- Day 43 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (43, 'DESIGN', 'HLD Mock #2 review', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'List 5 things you''d say differently next time', 0);
end $$;

-- Day 43 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (43, 'BEHAVIORAL', 'Salary/leveling research', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'levels.fyi, Blind, Glassdoor for target companies', 0);
end $$;

-- Day 44 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (44, 'DSA', 'Speed drill — Trees + Graphs', 'Speed focus', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '6 problems', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '25 min each', 1);
end $$;

-- Day 44 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (44, 'DESIGN', 'HLD Case Study — Online Code Editor', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Sandboxing, real-time execution (Leetcode/Replit)', 0);
end $$;

-- Day 44 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (44, 'BEHAVIORAL', 'Negotiation prep', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Read ''Ten Rules for Negotiating'' (haseebq) if not done', 0);
end $$;

-- Day 45 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (45, 'DSA', 'Speed drill — DP + Backtracking', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '5 problems', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '30 min each', 1);
end $$;

-- Day 45 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (45, 'DESIGN', 'HLD Case Study — Booking System', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Inventory locking, double-booking prevention (Airbnb/Hotel)', 0);
end $$;

-- Day 45 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (45, 'BEHAVIORAL', 'Questions for interviewer', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Prepare 3 sharp questions per round type', 0);
end $$;

-- Day 46 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (46, 'DSA', 'Mock Interview #4', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'DSA focused on your weakest topic from previous mocks', 0);
end $$;

-- Day 46 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (46, 'DESIGN', 'LLD Mock — Movie Booking System', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'BookMyShow with concurrency around seat locking', 0);
end $$;

-- Day 46 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (46, 'BEHAVIORAL', 'Self-recorded behavioral', 'Watch back', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '30 min, 5 prompts', 0);
end $$;

-- Day 47 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (47, 'DSA', 'Review Mock #4', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Patterns missed? Speed issues? Communication gaps?', 0);
end $$;

-- Day 47 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (47, 'DESIGN', 'HLD', 'Senior signal', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Feature flags, A/B testing infra, gradual rollouts', 0);
end $$;

-- Day 47 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (47, 'BEHAVIORAL', 'STAR pruning', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Take a 6 min answer and cut it to 3 min without losing impact', 0);
end $$;

-- Day 48 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (48, 'DSA', 'Onsite simulation', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '4 x 45 min DSA + 1 hour break + behavioral. Full endurance test', 0);
end $$;

-- Day 48 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (48, 'DESIGN', 'Design Task', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Review existing case study notes. No new HLD content today', 0);
end $$;

-- Day 48 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (48, 'BEHAVIORAL', 'Endurance assessment', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'How was hour 5? Plan rest before real onsite', 0);
end $$;

-- Day 49 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (49, 'DSA', 'Light DSA day', 'Read editorials', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '3 LC mediums', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'no time pressure', 1);
end $$;

-- Day 49 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (49, 'DESIGN', 'HLD Case Study — Payment System', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Idempotency, double-charge prevention, ledger', 0);
end $$;

-- Day 49 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (49, 'BEHAVIORAL', 'Final story bank', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Compile 12-15 polished stories indexed by theme', 0);
end $$;

-- Day 50 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (50, 'DSA', 'Phase 3 retrospective', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Are mock scores trending up? Identify final 2-3 gaps', 0);
end $$;

-- Day 50 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (50, 'DESIGN', 'HLD Case Study — Distributed Job Scheduler', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Cron at scale', 0);
end $$;

-- Day 50 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (50, 'BEHAVIORAL', 'Behavioral mock with senior engineer', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Get honest feedback', 0);
end $$;

-- Day 51 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (51, 'DSA', 'Must-know set', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'LRU Cache', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'LFU Cache', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Find Median from Data Stream', 2);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Trapping Rain Water', 3);
end $$;

-- Day 51 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (51, 'DESIGN', 'HLD speed-run', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Pick 5 case studies from your notes, do 10-min outlines each', 0);
end $$;

-- Day 51 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (51, 'BEHAVIORAL', 'Read engineering blogs', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Anthropic/Google/Meta — have a recent thing to discuss', 0);
end $$;

-- Day 52 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (52, 'DSA', 'Tagged — Final pass', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '8 problems for your top target', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'mix of high-frequency tags', 1);
end $$;

-- Day 52 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (52, 'DESIGN', 'Target company HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Design a system specific to your target company''s product', 0);
end $$;

-- Day 52 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (52, 'BEHAVIORAL', 'Top 5 stories final pass', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Record once, listen for filler words (um, like, sort of)', 0);
end $$;

-- Day 53 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (53, 'DSA', 'Mock Interview #5', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Full DSA simulation. 60 min', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'recorded. Solo or paid platform', 1);
end $$;

-- Day 53 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (53, 'DESIGN', 'HLD Mock #3', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Focus on deep-dive component, not just high level', 0);
end $$;

-- Day 53 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (53, 'BEHAVIORAL', 'Behavioral mock #3', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Timed, 30 min, recorded', 0);
end $$;

-- Day 54 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (54, 'DSA', 'Review all mocks', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Identify common gaps. Do 3 problems on those gaps', 0);
end $$;

-- Day 54 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (54, 'DESIGN', 'HLD weak areas review', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Capacity estimation accuracy, deep-dive specificity', 0);
end $$;

-- Day 54 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (54, 'BEHAVIORAL', 'Crisis stories', 'Polish them', 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Compile top 3 — performance issues, outages, conflicts', 0);
end $$;

-- Day 55 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (55, 'DSA', 'Light', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '2 LC mediums you''ve solved before', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'time them', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'aim for under 20 min each', 2);
end $$;

-- Day 55 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (55, 'DESIGN', 'HLD', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'DB internals deep-dive — B-tree vs LSM, isolation levels (common follow-ups)', 0);
end $$;

-- Day 55 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (55, 'BEHAVIORAL', 'Question bank', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Refresh your questions for each interviewer type', 0);
end $$;

-- Day 56 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (56, 'DSA', 'Speed drill', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '5 LC easies in 60 min. Should feel automatic now', 0);
end $$;

-- Day 56 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (56, 'DESIGN', 'LLD speed-run', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Re-implement Parking Lot, LRU Cache, BookMyShow seat locking from memory', 0);
end $$;

-- Day 56 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (56, 'BEHAVIORAL', 'Negotiation script', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Practice with specific numbers, ranges, walk-away point', 0);
end $$;

-- Day 57 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (57, 'DSA', 'Cool-down', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Re-solve 3 problems from Day 1. Measure how much faster you are', 0);
end $$;

-- Day 57 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (57, 'DESIGN', 'HLD numbers review', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Latency by component, QPS estimation, storage math', 0);
end $$;

-- Day 57 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (57, 'BEHAVIORAL', 'Why FAANG / why now', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Polish your 12 YoE story arc', 0);
end $$;

-- Day 58 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (58, 'DSA', 'Light', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '2 problems max. Don''t burn out', 0);
end $$;

-- Day 58 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (58, 'DESIGN', 'HLD outlines', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '2 case studies in 30 min each, outlines only', 0);
end $$;

-- Day 58 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (58, 'BEHAVIORAL', 'Behavioral final mock', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Go in fresh, treat as real interview', 0);
end $$;

-- Day 59 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (59, 'DSA', 'Rest day', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Review notes only. Walk', 0);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'exercise', 1);
  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'sleep early. No new problems', 2);
end $$;

-- Day 59 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (59, 'DESIGN', 'Rest day', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Skim HLD case study one-liners only', 0);
end $$;

-- Day 59 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (59, 'BEHAVIORAL', 'Mental prep', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Visualize the interview going well. Check logistics', 0);
end $$;

-- Day 60 · DSA
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (60, 'DSA', 'Warm-up', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, '1 easy problem for confidence. Then STOP', 0);
end $$;

-- Day 60 · DESIGN
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (60, 'DESIGN', 'Design Task', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Review your HLD framework one-pager only', 0);
end $$;

-- Day 60 · BEHAVIORAL
do $$
declare v_sec uuid;
begin
  insert into public.plan_sections (day_number, track, title, context_note, sort_order)
  values (60, 'BEHAVIORAL', 'Behavioral Task', NULL, 0)
  returning id into v_sec;

  insert into public.plan_items (section_id, title, sort_order)
  values (v_sec, 'Apply and schedule interviews. You''re ready', 0);
end $$;

